spring:
  application:
    name: sdjpa-inheritance

  docker:
    compose:
      enabled: false
      stop:
        command: down

  datasource:
    # we are using the h2 in compatible mode with mysql
    url: jdbc:h2:mem:sdjpa-inheritance-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.orm.jdbc.bind: INFO

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health/**
      - path: /h2-console/*

server:
  port: 8080
