---
apiVersion: v1
kind: Service
metadata:
  name: sdjpa-inheritance
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sdjpa-inheritance

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdjpa-inheritance
  labels:
    app: sdjpa-inheritance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdjpa-inheritance
  template:
    metadata:
      labels:
        app: sdjpa-inheritance
    spec:
      containers:
        - name: sdjpa-inheritance
          image: domboeckli/sdjpa-inheritance:0.0.1-SNAPSHOT
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6